//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface ModelCreateRequestDTO {
  guidId: string;
  modelName: string;
  modelTypesName: string;
}

export interface ModelGetRequestDTO {
  modelName: string;
}

export interface ModelResponseDTO {
  guidId: string;
  modelName: string;
  modelTypeName: string;
  modelVersions: ModelVersionResponseDTO[] | undefined;
}

export interface ModelTypeCreateRequestDTO {
  guidId: string;
  modelTypeName: string;
  testingModeGroupName: string;
}

export interface ModelTypeGetRequestDTO {
  modelTypeName: string;
}

export interface ModelTypeResponseDTO {
  modelTypeId: string;
  modelTypeName: string;
  models: ModelResponseDTO[] | undefined;
}

export interface ModelTypeUpdateRequestDTO {
  modelTypeId: string;
  modelTypeName: string;
  testingModeGroupName: string;
}

export interface ModelUpdateRequestDTO {
  modelId: string;
  modelName: string;
  modelTypesName: string;
}

export interface ModelVersionCreateRequestDTO {
  modelVersionId: number;
  versionDescription: string;
  modelVersionName: string;
  modelName: string;
  defaultTestingMode: string;
  timestamp: Date;
  userName: string;
  capacity: number;
  nominalOutput: number;
  nominalOutputPercentage: number;
  nonlinearityPercentage: number;
  minimumDeadLoad: number;
  vMin: number;
  nMax: number;
  safeLoad: number;
  ultimateLoad: number;
  shellMaterialName: string;
  alloy: boolean;
  defaultCableLength: number;
  numberOfGauges: number;
  resistance: number;
  cCNumber: string;
  accuracyClass: string;
  application: string;
  temperingHardnessLow: number;
  temperingHardnessHigh: number;
  nTEPCertificationId: string;
  nTEPCertificationTimestamp: Date;
  oIMLCertificationId: string;
  oIMLCertificationTimestamp: Date;
  testPointDirection: boolean;
  guidId: string;
}

export interface ModelVersionDocumentCreateRequestDTO {
  modelVersionId: number;
  modelName: string;
  modelVersionDocumentId: number;
  documentDescription: string;
  stage: string;
  documentDrive: string;
  documentPath: string;
  documentname: string;
  timestamp: Date;
  userName: string;
  guidId: string;
}

export interface ModelVersionDocumentGetRequestDTO {
  value: any | undefined;
}

export interface ModelVersionDocumentResponseDTO {
  value: any | undefined;
}

export interface ModelVersionDocumentUpdateRequestDTO {
  modelVersionId: number;
  modelName: string;
  modelVersionDocumentId: number;
  documentDescription: string;
  stage: string;
  documentDrive: string;
  documentPath: string;
  documentname: string;
  timestamp: Date;
  userName: string;
  guidId: string;
}

export interface ModelVersionGetRequestDTO {
  value: any | undefined;
}

export interface ModelVersionGroupCreateRequestDTO {
  testingModeGroupName: string;
  testingMode: string;
  description: string;
  guidId: string;
}

export interface ModelVersionGroupGetRequestDTO {
  value: any | undefined;
}

export interface ModelVersionGroupResponseDTO {
  testingModeGroupName: string;
  testingMode: string;
  description: string;
  guidId: string;
}

export interface ModelVersionGroupUpdateRequestDTO {
  testingModeGroupName: string;
  testingMode: string;
  description: string;
  guidId: string;
}

export interface ModelVersionResponseDTO {
  value: any | undefined;
}

export interface ModelVersionUpdateRequestDTO {
  modelVersionId: number;
  versionDescription: string;
  modelVersionName: string;
  modelName: string;
  defaultTestingMode: string;
  timestamp: Date;
  userName: string;
  capacity: number;
  nominalOutput: number;
  nominalOutputPercentage: number;
  nonlinearityPercentage: number;
  minimumDeadLoad: number;
  vMin: number;
  nMax: number;
  safeLoad: number;
  ultimateLoad: number;
  shellMaterialName: string;
  alloy: boolean;
  defaultCableLength: number;
  numberOfGauges: number;
  resistance: number;
  cCNumber: string;
  accuracyClass: string;
  application: string;
  temperingHardnessLow: number;
  temperingHardnessHigh: number;
  nTEPCertificationId: string;
  nTEPCertificationTimestamp: Date;
  oIMLCertificationId: string;
  oIMLCertificationTimestamp: Date;
  testPointDirection: boolean;
  guidId: string;
}

export interface ProductCreateRequestDTO {
  productId: number;
  modelVersionId: number;
  modelName: string;
  capacity: number;
  timestamp: Date;
  stage: string;
  subStage: string;
  salesOrderId: string;
  cableLength: number;
  inspectionResult: number;
  defaultTestingMode: string;
  testingModeGroupName: string;
  usedTestingMode: string;
  thermexPurcharseOrderNo: string;
  machiningPurcharseOrderNo: string;
  steelPurcharseOrderNo: string;
  batcNo: number;
  guidId: string;
}

export interface ProductGetRequestDTO {
  value: any | undefined;
}

export interface ProductResponseDTO {
  value: any | undefined;
}

export interface ProductUpdateRequestDTO {
  productId: number;
  modelVersionId: number;
  modelName: string;
  capacity: number;
  timestamp: Date;
  stage: string;
  subStage: string;

  salesOrderId: string;
  cableLength: number;

  inspectionResult: number;
  defaultTestingMode: string;
  testingModeGroupName: string;
  usedTestingMode: string;
  thermexPurcharseOrderNo: string;
  machiningPurcharseOrderNo: string;
  steelPurcharseOrderNo: string;
  batcNo: number;
  guidId: string;
}

export interface ShellMaterialCreateRequestDTO {
  shellMaterialName: string;
  alloy: boolean;
  guidId: string;
}

export interface ShellMaterialGetRequestDTO {
  value: any | undefined;
}

export interface ShellMaterialResponseDTO {
  value: any | undefined;
}

export interface ShellMaterialUpdateRequestDTO {
  shellMaterialName: string;
  alloy: boolean;
  guidId: string;
}

export interface TestPointCreateRequestDTO {
  modelVersionId: number;
  modelName: string;
  capacityTestPoint: number;
  guidId: string;
}

export interface TestPointGetRequestDTO {
  value: any | undefined;
}

export interface TestPointResponseDTO {
  value: any | undefined;
}

export interface TestPointUpdateRequestDTO {
  modelVersionId: number;
  modelName: string;
  capacityTestPoint: number;
  guidId: string;
}
