//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export type  ProblemRoot= {
  problemDetails: ProblemDetails;

}

export type ProblemDetails ={
  title: string;
  status: number;
  detail: string;
}

export interface ResultRoot {
  result: Result;
  status: number;
  title: string;
}

export interface Result {
  testingModeGroupName: string;
  testingMode: string;
  description: string;
  guidId: string;
}

export interface ModelCreateRequestDTO {
  guidId: string;
  modelName: string | undefined;
  modelTypesName: string | undefined;
}

export interface ModelGetRequestDTO {
  modelName: string | undefined;
}

export interface ModelResponseDTO {
  guidId: string;
  modelName: string | undefined;
  modelTypeName: string | undefined;
  modelVersions: ModelVersionResponseDTO[] | undefined;
}

export interface ModelTypeCreateRequestDTO {
  guidId: string;
  modelTypeName: string | undefined;
  testingModeGroupName: string | undefined;
}

export interface ModelTypeGetRequestDTO {
  modelTypeName: string | undefined;
}

export interface ModelTypeResponseDTO {
  modelTypeId: string | undefined;
  modelTypeName: string | undefined;
  models: ModelResponseDTO[] | undefined;
}

export interface ModelTypeUpdateRequestDTO {
  modelTypeId: string;
  modelTypeName: string | undefined;
  testingModeGroupName: string | undefined;
}

export interface ModelUpdateRequestDTO {
  modelId: string;
  modelName: string | undefined;
  modelTypesName: string | undefined;
}

export interface ModelVersionCreateRequestDTO {
  modelVersionId: number;
  versionDescription: string | undefined;
  modelVersionName: string | undefined;
  modelName: string | undefined;
  defaultTestingMode: string | undefined;
  timestamp: Date;
  userName: string | undefined;
  capacity: number;
  nominalOutput: number;
  nominalOutputPercentage: number;
  nonlinearityPercentage: number;
  minimumDeadLoad: number;
  vMin: number;
  nMax: number;
  safeLoad: number;
  ultimateLoad: number;
  shellMaterialName: string | undefined;
  alloy: boolean;
  defaultCableLength: number;
  numberOfGauges: number;
  resistance: number;
  cCNumber: string | undefined;
  accuracyClass: string | undefined;
  application: string | undefined;
  temperingHardnessLow: number;
  temperingHardnessHigh: number;
  nTEPCertificationId: string | undefined;
  nTEPCertificationTimestamp: Date;
  oIMLCertificationId: string | undefined;
  oIMLCertificationTimestamp: Date;
  testPointDirection: boolean;
  guidId: string;
}

export interface ModelVersionDocumentCreateRequestDTO {
  modelVersionId: number;
  modelName: string | undefined;
  modelVersionDocumentId: number;
  documentDescription: string | undefined;
  stage: string | undefined;
  documentDrive: string | undefined;
  documentPath: string | undefined;
  documentname: string | undefined;
  timestamp: Date;
  userName: string | undefined;
  guidId: string;
}

export interface ModelVersionDocumentGetRequestDTO {
  value: any | undefined;
}

export interface ModelVersionDocumentResponseDTO {
  value: any | undefined;
}

export interface ModelVersionDocumentUpdateRequestDTO {
  modelVersionId: number;
  modelName: string | undefined;
  modelVersionDocumentId: number;
  documentDescription: string | undefined;
  stage: string | undefined;
  documentDrive: string | undefined;
  documentPath: string | undefined;
  documentname: string | undefined;
  timestamp: Date;
  userName: string | undefined;
  guidId: string;
}

export interface ModelVersionGetRequestDTO {
  value: any | undefined;
}

export interface ModelVersionResponseDTO {
  value: any | undefined;
}

export interface ModelVersionUpdateRequestDTO {
  modelVersionId: number;
  versionDescription: string | undefined;
  modelVersionName: string | undefined;
  modelName: string | undefined;
  defaultTestingMode: string | undefined;
  timestamp: Date;
  userName: string | undefined;
  capacity: number;
  nominalOutput: number;
  nominalOutputPercentage: number;
  nonlinearityPercentage: number;
  minimumDeadLoad: number;
  vMin: number;
  nMax: number;
  safeLoad: number;
  ultimateLoad: number;
  shellMaterialName: string | undefined;
  alloy: boolean;
  defaultCableLength: number;
  numberOfGauges: number;
  resistance: number;
  cCNumber: string | undefined;
  accuracyClass: string | undefined;
  application: string | undefined;
  temperingHardnessLow: number;
  temperingHardnessHigh: number;
  nTEPCertificationId: string | undefined;
  nTEPCertificationTimestamp: Date;
  oIMLCertificationId: string | undefined;
  oIMLCertificationTimestamp: Date;
  testPointDirection: boolean;
  guidId: string;
}

export interface ProductCreateRequestDTO {
  productId: number;
  modelVersionId: number;
  modelName: string | undefined;
  capacity: number;
  timestamp: Date;
  stage: string | undefined;
  subStage: string | undefined;
  salesOrderId: string | undefined;
  cableLength: number;
  inspectionResult: number;
  defaultTestingMode: string | undefined;
  testingModeGroupName: string | undefined;
  usedTestingMode: string | undefined;
  thermexPurcharseOrderNo: string | undefined;
  machiningPurcharseOrderNo: string | undefined;
  steelPurcharseOrderNo: string | undefined;
  batcNo: number;
  guidId: string;
}

export interface ProductGetRequestDTO {
  value: any | undefined;
}

export interface ProductResponseDTO {
  value: any | undefined;
}

export interface ProductUpdateRequestDTO {
  productId: number;
  modelVersionId: number;
  modelName: string | undefined;
  capacity: number;
  timestamp: Date;
  stage: string | undefined;
  subStage: string | undefined;
  salesOrderId: string | undefined;
  cableLength: number;
  inspectionResult: number;
  defaultTestingMode: string | undefined;
  testingModeGroupName: string | undefined;
  usedTestingMode: string | undefined;
  thermexPurcharseOrderNo: string | undefined;
  machiningPurcharseOrderNo: string | undefined;
  steelPurcharseOrderNo: string | undefined;
  batcNo: number;
  guidId: string;
}

export interface ShellMaterialCreateRequestDTO {
  shellMaterialName: string | undefined;
  alloy: boolean;
  guidId: string;
}

export interface ShellMaterialGetRequestDTO {
  value: any | undefined;
}

export interface ShellMaterialResponseDTO {
  value: any | undefined;
}

export interface ShellMaterialUpdateRequestDTO {
  shellMaterialName: string | undefined;
  alloy: boolean;
  guidId: string;
}

export interface TestPointCreateRequestDTO {
  modelVersionId: number;
  modelName: string | undefined;
  capacityTestPoint: number;
  guidId: string;
}

export interface TestPointGetRequestDTO {
  value: any | undefined;
}

export interface TestPointResponseDTO {
  value: any | undefined;
}

export interface TestPointUpdateRequestDTO {
  modelVersionId: number;
  modelName: string | undefined;
  capacityTestPoint: number;
  guidId: string;
}

export interface TestingModeGroupCreateRequestDTO {
  testingModeGroupName: string | undefined;
  testingMode: string | undefined;
  description: string | undefined;
  guidId: string;
}

export interface TestingModeGroupGetRequestDTO {
  value: any | undefined;
}

export interface TestingModeGroupResponseDTO {
  testingModeGroupName: string | undefined;
  testingMode: string | undefined;
  description: string | undefined;
  guidId: string;
}

export type TTestingModeGroupResponseDTO = {
  result: TestingModeGroupResponseDTO[];
};

export interface TestingModeGroupUpdateRequestDTO {
  testingModeGroupName: string | undefined;
  testingMode: string | undefined;
  description: string | undefined;
  guidId: string;
}
