import { GridValidRowModel } from '@mui/x-data-grid';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const samplenewrows: GridValidRowModel[] = [
  {
    id: '1',
    testingModeGroupName: 'group1',
    testingMode: 'test',
    description: 'desc',
    guidId: 'guid1',
  },
  {
    id: '2',
    testingModeGroupName: 'group2',
    testingMode: 'test2',
    description: 'desc2',
    guidId: 'guid2',
  },
  {
    id: '3',
    testingModeGroupName: 'group3',
    testingMode: 'test3',
    description: 'desc3',
    guidId: 'guid3',
  },
  {
    id: '4',
    testingModeGroupName: 'group4',
    testingMode: 'test4',
    description: 'desc4',
    guidId: 'guid4',
  },
  {
    id: '5',
    testingModeGroupName: 'group5',
    testingMode: 'test5',
    description: 'desc5',
    guidId: 'guid5',
  },
  {
    id: '6',
    testingModeGroupName: 'group6',
    testingMode: 'test6',
    description: 'desc6',
    guidId: 'guid6',
  },
  {
    id: '7',
    testingModeGroupName: 'group7',
    testingMode: 'test7',
    description: 'desc7',
    guidId: 'guid7',
  },
  {
    id: '8',
    testingModeGroupName: 'group8',
    testingMode: 'test8',
    description: 'desc8',
    guidId: 'guid8',
  },
  {
    id: '9',
    testingModeGroupName: 'group9',
    testingMode: 'test9',
    description: 'desc9',
    guidId: 'guid9',
  },
  {
    id: '10',
    testingModeGroupName: 'group10',
    testingMode: 'test10',
    description: 'desc10',
    guidId: 'guid10',
  },
  {
    id: '11',
    testingModeGroupName: 'group11',
    testingMode: 'test11',
    description: 'desc11',
    guidId: 'guid11',
  },
  {
    id: '12',
    testingModeGroupName: 'group12',
    testingMode: 'test12',
    description: 'desc12',
    guidId: 'guid12',
  },
  {
    id: '13',
    testingModeGroupName: 'group13',
    testingMode: 'test13',
    description: 'desc13',
    guidId: 'guid13',
  },
  {
    id: '14',
    testingModeGroupName: 'group14',
    testingMode: 'test14',
    description: 'desc14',
    guidId: 'guid14',
  },
]; // Declare the newrows variable
